/**
 * Airport code → name lookup (IATA 3-letter and ICAO 4-letter).
 * Major commercial airports for tooltip/popup display.
 */
export const AIRPORT_NAMES = {
  FRA: "Frankfurt am Main", EDDF: "Frankfurt am Main",
  LAX: "Los Angeles International", KLAX: "Los Angeles International",
  MIA: "Miami International", KMIA: "Miami International",
  JFK: "New York JFK", KJFK: "New York JFK",
  ORD: "Chicago O'Hare", KORD: "Chicago O'Hare",
  DFW: "Dallas Fort Worth", KDFW: "Dallas Fort Worth",
  ATL: "Atlanta Hartsfield-Jackson", KATL: "Atlanta Hartsfield-Jackson",
  LHR: "London Heathrow", EGLL: "London Heathrow",
  CDG: "Paris Charles de Gaulle", LFPG: "Paris Charles de Gaulle",
  AMS: "Amsterdam Schiphol", EHAM: "Amsterdam Schiphol",
  FCO: "Rome Fiumicino", LIRF: "Rome Fiumicino",
  MAD: "Madrid Barajas", LEMD: "Madrid Barajas",
  BCN: "Barcelona El Prat", LEBL: "Barcelona El Prat",
  MUC: "Munich", EDDM: "Munich",
  ZRH: "Zurich", LSZH: "Zurich",
  VIE: "Vienna", LOWW: "Vienna",
  DUB: "Dublin", EIDW: "Dublin",
  LIS: "Lisbon", LPPT: "Lisbon",
  NRT: "Tokyo Narita", RJAA: "Tokyo Narita",
  HND: "Tokyo Haneda", RJTT: "Tokyo Haneda",
  PEK: "Beijing Capital", ZBAA: "Beijing Capital",
  PVG: "Shanghai Pudong", ZSPD: "Shanghai Pudong",
  HKG: "Hong Kong", VHHH: "Hong Kong",
  SIN: "Singapore Changi", WSSS: "Singapore Changi",
  DXB: "Dubai", OMDB: "Dubai",
  DOH: "Doha Hamad", OTHH: "Doha Hamad",
  IAH: "Houston Bush", KIAH: "Houston Bush",
  SFO: "San Francisco", KSFO: "San Francisco",
  SEA: "Seattle Tacoma", KSEA: "Seattle Tacoma",
  DEN: "Denver", KDEN: "Denver",
  PHX: "Phoenix Sky Harbor", KPHX: "Phoenix Sky Harbor",
  BOS: "Boston Logan", KBOS: "Boston Logan",
  EWR: "Newark Liberty", KEWR: "Newark Liberty",
  LGA: "New York LaGuardia", KLGA: "New York LaGuardia",
  MCO: "Orlando", KMCO: "Orlando International",
  LAS: "Las Vegas McCarran", KLAS: "Las Vegas McCarran",
  MSP: "Minneapolis St Paul", KMSP: "Minneapolis St Paul",
  DTW: "Detroit Metropolitan", KDTW: "Detroit Metropolitan",
  PHL: "Philadelphia", KPHL: "Philadelphia",
  CLT: "Charlotte Douglas", KCLT: "Charlotte Douglas",
  DCA: "Washington Reagan", KDCA: "Washington Reagan",
  IAD: "Washington Dulles", KIAD: "Washington Dulles",
  FLL: "Fort Lauderdale", KFLL: "Fort Lauderdale",
  TPA: "Tampa", KTPA: "Tampa",
  BWI: "Baltimore Washington", KBWI: "Baltimore Washington",
  AUS: "Austin Bergstrom", KAUS: "Austin Bergstrom",
  BNA: "Nashville", KBNA: "Nashville",
  MSY: "New Orleans", KMSY: "New Orleans",
  RDU: "Raleigh Durham", KRDU: "Raleigh Durham",
  MAN: "Manchester", EGCC: "Manchester",
  BHX: "Birmingham UK", EGBB: "Birmingham UK",
  EDI: "Edinburgh", EGPH: "Edinburgh",
  GVA: "Geneva", LSGG: "Geneva",
  BRU: "Brussels", EBBR: "Brussels",
  CPH: "Copenhagen", EKCH: "Copenhagen",
  ARN: "Stockholm Arlanda", ESSA: "Stockholm Arlanda",
  OSL: "Oslo Gardermoen", ENGM: "Oslo Gardermoen",
  HEL: "Helsinki", EFHK: "Helsinki",
  WAW: "Warsaw Chopin", EPWA: "Warsaw Chopin",
  PRG: "Prague", LKPR: "Prague",
  BUD: "Budapest", LHBP: "Budapest",
  ATH: "Athens", LGAV: "Athens",
  IST: "Istanbul", LTFM: "Istanbul",
  TLV: "Tel Aviv Ben Gurion", LLBG: "Tel Aviv Ben Gurion",
  CAI: "Cairo", HECA: "Cairo",
  JNB: "Johannesburg", FAOR: "Johannesburg",
  SYD: "Sydney", YSSY: "Sydney",
  MEL: "Melbourne", YMML: "Melbourne",
  AKL: "Auckland", NZAA: "Auckland",
  EZE: "Buenos Aires Ezeiza", SAEZ: "Buenos Aires Ezeiza",
  GRU: "São Paulo Guarulhos", SBGR: "São Paulo Guarulhos",
  MEX: "Mexico City", MMMX: "Mexico City",
  YYZ: "Toronto Pearson", CYYZ: "Toronto Pearson",
  YVR: "Vancouver", CYVR: "Vancouver",
  CUN: "Cancún", MMUN: "Cancún",
  SJU: "San Juan", TJSJ: "San Juan",
  BOG: "Bogotá", SKBO: "Bogotá",
  PTY: "Panama City Tocumen", MPMG: "Panama City Tocumen",
  SCL: "Santiago", SCEL: "Santiago",
  LIM: "Lima", SPIM: "Lima",
  BAH: "Bahrain", OBBI: "Bahrain",
  KUL: "Kuala Lumpur", WMKK: "Kuala Lumpur",
  BKK: "Bangkok Suvarnabhumi", VTBS: "Bangkok Suvarnabhumi",
  MNL: "Manila", RPLL: "Manila",
  CGK: "Jakarta", WIII: "Jakarta",
  BOM: "Mumbai", VABB: "Mumbai",
  DEL: "Delhi Indira Gandhi", VIDP: "Delhi Indira Gandhi",
  DME: "Moscow Domodedovo", UUDD: "Moscow Domodedovo",
  SVO: "Moscow Sheremetyevo", UUEE: "Moscow Sheremetyevo",
  LED: "St Petersburg", ULLI: "St Petersburg",
  OPO: "Porto", LPPR: "Porto",
  LYS: "Lyon", LFLL: "Lyon",
  NCE: "Nice", LFMN: "Nice",
  TLS: "Toulouse", LFBO: "Toulouse",
  NTE: "Nantes", LFRS: "Nantes",
  BOD: "Bordeaux", LFBD: "Bordeaux",
  HAM: "Hamburg", EDDH: "Hamburg",
  DUS: "Düsseldorf", EDDL: "Düsseldorf",
  STR: "Stuttgart", EDDS: "Stuttgart",
  CGN: "Cologne Bonn", EDDK: "Cologne Bonn",
  BRE: "Bremen", EDDW: "Bremen",
  HAJ: "Hannover", EDDV: "Hannover",
  NUE: "Nuremberg", EDDN: "Nuremberg",
  PMI: "Palma de Mallorca", LEPA: "Palma de Mallorca",
  VCE: "Venice Marco Polo", LIPZ: "Venice Marco Polo",
  MXP: "Milan Malpensa", LIMC: "Milan Malpensa",
  LIN: "Milan Linate", LIML: "Milan Linate",
  FCO: "Rome Fiumicino", LIRF: "Rome Fiumicino",
  NAP: "Naples", LIRN: "Naples",
  TXL: "Berlin Tegel", EDDT: "Berlin Tegel",
  SXF: "Berlin Schönefeld", EDDB: "Berlin Schönefeld",
  BER: "Berlin Brandenburg", EDDB: "Berlin Brandenburg",
  DUB: "Dublin", EIDW: "Dublin",
  SNN: "Shannon", EINN: "Shannon",
  BFS: "Belfast", EGAC: "Belfast",
  GLA: "Glasgow", EGPF: "Glasgow",
  LTN: "London Luton", EGGW: "London Luton",
  STN: "London Stansted", EGSS: "London Stansted",
  LGW: "London Gatwick", EGKK: "London Gatwick",
  LBA: "Leeds Bradford", EGNM: "Leeds Bradford",
  BRS: "Bristol", EGGD: "Bristol",
  NCL: "Newcastle", EGNT: "Newcastle",
  CWL: "Cardiff", EGFF: "Cardiff",
  BHD: "Belfast City", EGAC: "Belfast City"
};

export function getAirportName(code) {
  if (!code || typeof code !== "string") return null;
  const c = code.trim().toUpperCase();
  return AIRPORT_NAMES[c] || null;
}

/** Format "FRA (Frankfurt am Main)" or just "FRA" if unknown */
export function formatAirportWithName(code) {
  if (!code || typeof code !== "string") return "—";
  const name = getAirportName(code.trim());
  return name ? `${code.trim()} (${name})` : code.trim();
}
